### ISSUE TITLE
Error: Cannot find module 'xmldom' with latest

### ISSUE THREAD

**Issue by nathanks** [ExLibrisGroup/exl-touchnet-connector#13]
We're having trouble starting the latest container image.  We are getting the following error message:

2021-09-27T13:05:39.415Z INFO  - Initiating warmup request to container _0_33f3a314 for site

2021-09-27T13:05:40.712138485Z internal/modules/cjs/loader.js:969
2021-09-27T13:05:40.712174288Z   throw err;
2021-09-27T13:05:40.712179688Z   ^
2021-09-27T13:05:40.712183489Z
2021-09-27T13:05:40.712187189Z Error: Cannot find module 'xmldom'
2021-09-27T13:05:40.712190889Z Require stack:
2021-09-27T13:05:40.712194490Z - /usr/src/app/node_modules/almarestapi-lib/alma.js
2021-09-27T13:05:40.712205090Z - /usr/src/app/app/index.js
2021-09-27T13:05:40.712208991Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
2021-09-27T13:05:40.712213391Z     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
2021-09-27T13:05:40.712217192Z     at Module.require (internal/modules/cjs/loader.js:1026:19)
2021-09-27T13:05:40.712220892Z     at require (internal/modules/cjs/helpers.js:72:18)
2021-09-27T13:05:40.712224692Z     at Object.<anonymous> (/usr/src/app/node_modules/almarestapi-lib/alma.js:3:18)
2021-09-27T13:05:40.712228893Z     at Module._compile (internal/modules/cjs/loader.js:1138:30)
2021-09-27T13:05:40.712232593Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2021-09-27T13:05:40.712236293Z     at Module.load (internal/modules/cjs/loader.js:986:32)
2021-09-27T13:05:40.712239893Z     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2021-09-27T13:05:40.712243494Z     at Module.require (internal/modules/cjs/loader.js:1026:19) {
2021-09-27T13:05:40.712247094Z   code: 'MODULE_NOT_FOUND',
2021-09-27T13:05:40.712250694Z   requireStack: [
2021-09-27T13:05:40.712254195Z     '/usr/src/app/node_modules/almarestapi-lib/alma.js',
2021-09-27T13:05:40.712257795Z     '/usr/src/app/app/index.js'
2021-09-27T13:05:40.712261395Z   ]
2021-09-27T13:05:40.712264896Z }

2021-09-27T13:05:41.576Z ERROR - Container _0_33f3a314 for site has exited, failing site start

**Comment by jweisman** [comment]
Hi @nathanks - thanks for your issue. The docker image has been updated on docker hub. Can you check again?

**Comment by nathanks** [comment]
Yes, looks good now.  No more error.
